name: Clone Bitbucket Repository

on: [push]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Clone bitbucket
        run: git clone https://x-token-auth:${{ secrets.BITBUCKET_API_TOKEN }}@bitbucket.org/n_piper/personal-mba.git

      - name: Where am I?
        run: pwd && ls -ltra

      - name: Change Dir
        run: cd personal-mba

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: cd personal-mba && npm install

      - name: Install Antora
        run: cd personal-mba && npm i antora

      - name: Generate Site
        run: cd personal-mba && npx antora antora-playbook.yml

      - name: Show site contents
        run: cd personal-mba/dist && ls -ltra

        
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./personal-mba/DIST